Add coverage field
bitrise-steplib/steps-gitlab-status pull request #13
Opened 2019-07-25 20:13 UTC by mvolpato

Add the possibility to send the test coverage to the GitLab instance. 
Test coverage must be a float, otherwise it is discarded.
The value can be calculated in a previous step and saved in an environment variable that then can be used in this step.

2019-11-05 08:58 UTC, richard-bogdan-bitrise requested changes
Please check the added comments and fix them.

2019-11-05 08:58 UTC, richard-bogdan-bitrise commented on main.go
> +		log.Warnf("Coverage is not a representation of a floting point number: setting it to 0.0.")
typo, floating

2019-11-05 08:58 UTC, richard-bogdan-bitrise commented on step.yml
> +        Must be a representation of a floating number. If not, it will be discarded.
Please indicate, that the maximum is 100.0.

2019-11-05 08:58 UTC, richard-bogdan-bitrise commented on main.go
> +	    form.Add("coverage", coverage)
Please limit it to 100.0. Maybe a warning message should be useful, if it is higher than the maximum.

2019-11-13 16:06 UTC, richard-bogdan-bitrise commented
Thanks for the PR, but due to unresponsiveness I implemented it, and it has been merged, so I am closing this.

2019-11-13 16:06 UTC, closed without merging

2019-11-14 11:27 UTC, mvolpato commented
> Thanks for the PR, but due to unresponsiveness I implemented it, and it has been merged, so I am closing this.

Hi, thanks.
Sorry for not responding, I was on holiday.

2021-01-15 08:47 UTC, afaucogney commented
Hey @richard-bogdan-bitrise / @mvolpato , does this feature works ? I have some issue with it.

```
+------------------------------------------------------------------------------+
| (10) gitlab-status                                                           |
+------------------------------------------------------------------------------+
| id: gitlab-status                                                            |
| version: 0.12.4                                                              |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-01-14T18:33:03Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Error: failed to parse config:
- Coverage: 21.1
: failed to parse value 21.1
: value 21.1
 is could not be parsed
```

2021-01-15 09:48 UTC, richard-bogdan-bitrise commented
Hey @afaucogney,
Thanks for reporting it, we will look at this issue soon.

2021-01-27 14:11 UTC, afaucogney commented
Hu @richard-bogdan-bitrise did you had to chance to check that issue ?

2021-01-27 15:04 UTC, richard-bogdan-bitrise commented
Hey @afaucogney, 
Apologies, but currently I am working on a different issue, fellow teammates are checking it and will get back to you, when they are ready.

2021-02-03 11:08 UTC, afaucogney commented
@richard-bogdan-bitrise for info, I push a support ticket. Feel free to have a look and remind it to your fellow teammates. https://bitrise.zendesk.com/hc/en-us/requests/11101

2021-02-03 11:19 UTC, richard-bogdan-bitrise commented
@afaucogney: thank you, forwarded the support ticket to the team and will push them. Thank you for your patience!